version: '3.8'

services:
  # MongoDB database
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - unsplash-network

  # Unsplash Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: unsplash-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - IMAGE_SERVICE_URL=http://image-service:3001
    networks:
      - unsplash-network
    depends_on:
      - image-service

  # Image Service
  image-service:
    build:
      context: ./image-service
      dockerfile: Dockerfile
    container_name: image-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/unsplash-images
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
      - NODE_ENV=production
    networks:
      - unsplash-network
    depends_on:
      - mongo

  # Gallery Service
  gallery-service:
    build:
      context: ./gallery-service
      dockerfile: Dockerfile
    container_name: gallery-service
    ports:
      - "3002:3002"
    environment:
      - IMAGE_SERVICE_URL=http://image-service:3001
      - NODE_ENV=production
    networks:
      - unsplash-network
    depends_on:
      - image-service

networks:
  unsplash-network:
    driver: bridge

volumes:
  mongo-data: 